[package]
name = "number_factory"
version = "0.1.0"
authors = ["larsfinlay <larsfinlay@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.7.0"
rand = "0.7.3"
